name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3
    
    

    # Set up Google Cloud credentials
    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{secrets.PROVIDER_NAME}}
        service_account: ${{secrets.SERVICE_ACCOUNT_EMAIL}}

    # Setup Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.1

    # Terraform Init
    - name: Terraform Init
      run: terraform init

    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="/gke-terraform-git-action-example/terraform.tfvars"

    
